# Usa una imagen base de Java 21
FROM eclipse-temurin:21-jdk

# Crea un directorio de trabajo
WORKDIR /app

# Copia el JAR generado
COPY target/*-runner.jar app.jar

# Expone el puerto 8081 (tu app corre en ese puerto)
EXPOSE 8081

# Comando para ejecutar tu aplicación
ENTRYPOINT ["java", "-jar", "app.jar"]
